def make_lessons(rows):
    return [{"title":t,"body":f"In Plain English\n{ex}\n\nWhy This Matters\n{why}\n\nTry It Yourself\n{tryit}\n\nCommon Mistake\n{mistake}\n\nLevel Up\n{level}"} for t,ex,why,tryit,mistake,level in rows]

COURSES=[
{"slug":"ai","title":"AI Fundamentals","tag":"AI","description":"Learn how AI works: data, machine learning, neural networks, LLMs, embeddings, agents, evaluation, and safe AI projects.","lessons":make_lessons([
("What Is AI?","AI is software that finds patterns, makes predictions, or generates useful output. A calculator follows fixed rules; a learned model uses patterns discovered from examples.","It gives you a mental model for everything else in AI.","Classify three tasks as rules, prediction, generation, or search.","Thinking every AI system is a conscious brain.","Build a tiny rule-based classifier and compare it with learned AI."),
("Data: The Fuel","Models learn from examples: text, images, audio, numbers, clicks, and more. Labels tell a supervised model what an example represents.","Bad or unrepresentative data can produce bad behavior even with a powerful model.","Design a balanced dataset for a cat-photo classifier.","Assuming more data always means better data.","Invent three edge cases your dataset must include."),
("Machine Learning","Machine learning learns patterns from examples instead of requiring every decision to be manually coded. Training adjusts a model; inference uses the trained model on new input.","Training versus inference is the basic loop behind many AI products.","Sort examples into training and inference.","Treating training accuracy as proof the model works on new data.","Explain overfitting in one sentence."),
("Neural Networks","A neural network is a mathematical function made from layers of parameterized units. Inputs move forward through layers; training changes weights to improve predictions.","This is the engine behind many modern vision, language, and speech systems.","Draw pixels → features → prediction for an image model.","Calling a neural network a digital brain.","Use the lab visualizer to change simple feature weights."),
("Generative AI & LLMs","Generative AI creates text, images, audio, or code. LLMs process tokens and repeatedly predict likely next tokens using patterns learned from large datasets.","It explains why context, examples, and constraints change model output.","Rewrite one vague prompt into a precise prompt with an output format.","Assuming confident text is automatically factual.","Create a reusable Role + Goal + Context + Constraints prompt template."),
("Embeddings & Semantic Search","An embedding represents information as numbers so related items can be compared in vector space. Semantic search retrieves by meaning rather than exact words.","Embeddings power search, recommendations, clustering, and retrieval systems.","Choose which of three short notes should be closest in meaning to a query.","Confusing similarity with truth.","Design a tiny course-search system using embeddings conceptually."),
("Agents, Tools & Safety","An AI agent combines a model with tools, state, rules, and a loop. Safe agents validate tool inputs, limit permissions, log actions, and require confirmation for sensitive operations.","The useful part of an agent is controlled action, not giving a model unlimited access.","Design an agent that can read a calendar but needs approval before sending anything.","Using model output as the security boundary.","Map goal → model → tool → validation → result → model."),
("AI Capstone","Build a small AI-flavored project: a prompt playground, classifier, semantic-search demo, study helper, recommender, or agent simulator. Keep it understandable.","Shipping a small tested project turns concepts into actual skill.","Build the smallest version, test weird inputs, explain failure cases, and add one safety rule.","Adding features before the basic version works.","Document what your system can and cannot reliably do.")
])},
{"slug":"go","title":"Go (Golang)","tag":"GO","description":"Learn Go from zero through syntax, types, control flow, functions, collections, structs, interfaces, errors, concurrency, and a CLI project.","lessons":make_lessons([
("Meet Go","Go is a compiled language designed around simple syntax, fast builds, readable code, and practical software engineering. Programs use package main and func main().","You can use the same small structure to grow into real tools and services.","Write a program that prints your name and a goal.","Leaving unused imports or variables in a program.","Predict what the Go compiler will reject before running it."),
("Variables & Types","Go has types such as string, int, float64, and bool. Short declaration with := is convenient inside functions; = assigns to an existing variable.","Types let the compiler catch many mistakes early.","Model a game character with name, level, health, and alive.","Using := when you meant to update an existing variable.","Try converting between numeric types deliberately."),
("If, Switch & For","Go uses if, switch, and one loop keyword: for. A loop can behave like a classic counter, while loop, or infinite loop.","These simple control-flow tools are enough for a huge amount of real code.","Print even levels from 1 to 10.","Looking for a while keyword; Go uses for with a condition.","Use switch to map character classes to starting stats."),
("Functions","Functions package reusable behavior. Parameters and return types form a clear contract, and Go commonly returns both a result and an error.","Small functions make programs easier to test and understand.","Write a score-to-rank function.","Making one giant main function that does everything.","Return (value, error) from a validation function."),
("Slices & Maps","Slices are flexible ordered collections; maps store key-value pairs. append grows a slice, while map keys provide fast lookup.","Collections let your program handle real sets of changing data.","Build an inventory slice and a player-score map.","Assuming a missing map key automatically means the key existed.","Use the comma-ok pattern for a map lookup."),
("Structs & Interfaces","Structs group related fields into a custom type. Interfaces describe behavior through methods; a type satisfies an interface by implementing those methods.","They let Go model real things without complicated inheritance trees.","Create Player and Item structs.","Thinking interfaces require an explicit implements declaration.","Make two different types satisfy one small interface."),
("Errors & Concurrency","Go treats errors as ordinary return values. Goroutines run functions concurrently, while channels can coordinate communication between concurrent work.","Reliable programs need explicit failure handling and controlled concurrency.","List three failures your project should handle.","Assuming concurrency automatically makes code faster or simpler.","Sketch a worker that sends results through a channel."),
("Go Capstone","Build a CLI tool such as a todo list, habit tracker, expense tracker, quiz game, or file utility. Use functions, structs, collections, and explicit error handling.","A small command-line project forces you to use Go as a language rather than memorizing syntax.","Build one command first, then add data and validation.","Trying to build a huge framework before the core feature works.","Add tests and make the tool survive bad input.")
])},
{"slug":"typescript","title":"TypeScript","tag":"TS","description":"Learn TypeScript from zero: types, objects, functions, unions, narrowing, interfaces, generics, async code, APIs, and clean app design.","lessons":make_lessons([
("Why TypeScript?","TypeScript adds static types and tooling to JavaScript. It is transformed into JavaScript, so browsers and JavaScript runtimes can execute the result.","Types make large projects easier to understand and refactor.","Give a username and score explicit types.","Using any everywhere just to silence errors.","Replace an any with a precise type."),
("Objects & Arrays","TypeScript can describe object shapes and arrays. A type can document exactly which fields a value should have.","Shared data becomes easier to use correctly across a project.","Create a Player type and an array of players.","Forgetting that external JSON is still untrusted at runtime.","Model nested course data."),
("Functions & Aliases","Functions can type parameters and return values. Type aliases give reusable names to complex shapes.","Clear contracts make autocomplete and refactoring much safer.","Write a typed function that formats a player's score.","Leaving important return types vague in shared utilities.","Create a reusable ID = string | number alias."),
("Unions & Narrowing","A union such as string | number means a value can be one of several types. Narrowing checks which case you have before using it.","Real APIs often contain multiple valid states or shapes.","Create a Status union with loading, success, and error.","Treating a union like it is all its members at once.","Use typeof or an in-check to narrow an object."),
("Interfaces & Classes","Interfaces describe object contracts. Classes can bundle state and behavior when that model actually helps.","Interfaces are useful boundaries between parts of an application.","Define an interface for a Course.","Assuming interfaces perform runtime validation.","Pair a TypeScript interface with a runtime validation function."),
("Generics","Generics let reusable code preserve type information. A function such as first<T>(items: T[]) can work with many types without losing what T is.","Generics are everywhere in serious TypeScript libraries.","Write a typed last-item function.","Thinking generic means the value has no useful constraints.","Create a Result<T> type for success or failure."),
("Async, APIs & Modules","async and await make promise-based work easier to read. Modules split code into files, while API calls bring external data into the application.","Most real apps communicate with services asynchronously.","Design loading, success, and error states for one API request.","Typing a response does not prove the server sent valid data.","Add runtime validation to an API response."),
("TypeScript Capstone","Build a task manager, quiz, inventory tracker, dashboard, or small API client. Use custom types, typed functions, a union, and an async flow.","A project reveals where types genuinely help instead of turning them into decoration.","Define the data model first, then build the smallest working feature.","Making the compiler happy by hiding problems with any.","Remove unnecessary any and explain every remaining escape hatch.")
])},
{"slug":"html","title":"HTML","tag":"HTML","description":"Build real web pages from zero: structure, semantics, links, images, lists, tables, forms, accessibility, metadata, and a complete landing page.","lessons":make_lessons([
("The Web Page Skeleton","HTML describes document structure and meaning. CSS handles presentation and JavaScript handles behavior.","Every web interface starts with a structure the browser can understand.","Build a page with doctype, html, body, h1, and p.","Treating HTML like a programming language.","Open your page with CSS disabled and see whether the structure still makes sense."),
("Semantic Structure","Elements such as header, nav, main, section, article, and footer communicate meaning instead of merely creating boxes.","Semantic markup improves readability, accessibility, and maintainability.","Turn a div-only page into semantic sections.","Choosing elements only because their default appearance looks right.","Create a semantic course page."),
("Links & Images","Anchors connect pages and resources. Images can provide information and should have useful alt text when needed.","Navigation and visual content are core parts of the web.","Create a profile with two links and one meaningful image.","Using vague alt text or forgetting that decorative images can use empty alt text.","Make a small navigation menu."),
("Lists & Tables","Use ul or ol for lists and tables for actual row-and-column data. Do not use tables as a layout hack.","The correct structure makes information easier to scan and interpret.","Build a game inventory and score table.","Using a table to position cards on a page.","Add clear table headings."),
("Forms","Forms collect user input with controls such as input, textarea, select, and button. Labels connect instructions to controls.","Forms power search, signup, login, checkout, and contact flows.","Build a signup form with name, email, password, and submit button.","Using a placeholder instead of a real label.","Add useful validation attributes and field names."),
("Accessibility","Accessible pages consider keyboard users, screen readers, contrast, labels, focus, alt text, and logical document structure.","A page is not finished if some people cannot use its interface.","Add labels, a logical heading hierarchy, and descriptive link text.","Skipping headings just to get a particular visual size.","Navigate your page using only the keyboard."),
("Metadata & Page Quality","The head can contain a title, description, language information, viewport settings, and other metadata. Good structure also helps search and sharing.","Browsers and other systems need context about your document.","Add a useful title, description, lang attribute, and viewport meta tag.","Putting visible page content inside the head.","Create a share-ready landing page structure."),
("HTML Capstone","Build a complete semantic landing page for a portfolio, course, game, project, or fictional startup. Include navigation, sections, media, lists, a form, and footer.","A complete page turns isolated elements into an actual website structure.","Build the smallest version, then improve semantics and accessibility.","Stuffing everything into one giant div.","Disable CSS and verify the page still reads logically.")
])},
{"slug":"css","title":"CSS","tag":"CSS","description":"Make the web look good: selectors, specificity, the box model, Flexbox, Grid, responsive design, variables, animation, and a polished interface.","lessons":make_lessons([
("CSS Basics","CSS controls appearance: typography, spacing, colors, borders, layout, effects, and responsive behavior.","HTML gives structure; CSS turns that structure into an interface.","Style a heading and card from scratch.","Writing a selector that never matches the HTML.","Inspect an element and trace which rule controls it."),
("Selectors & Specificity","Selectors target elements using tags, classes, IDs, attributes, states, and relationships. Specificity helps determine which matching rule wins.","Predictable selectors keep projects maintainable.","Style cards and their hover state.","Using !important for every conflict.","Rewrite an overly specific selector into a simpler one."),
("The Box Model","Every element has content, padding, border, and margin. box-sizing: border-box makes width calculations easier to reason about.","Most mysterious spacing bugs are easier once you see the box model.","Change padding, border, and margin one at a time.","Confusing margin outside the box with padding inside it.","Build a card with controlled dimensions."),
("Flexbox","Flexbox arranges items along a main axis and gives you alignment, spacing, wrapping, and ordering tools.","It is ideal for navbars, toolbars, rows, and one-dimensional layouts.","Make three cards align in a row and wrap on small screens.","Using absolute positioning for every layout.","Build a responsive navigation bar with Flexbox."),
("CSS Grid","Grid handles two-dimensional rows and columns. fr units, gap, minmax, and repeat make responsive layouts concise.","Course cards, galleries, dashboards, and page layouts often fit Grid naturally.","Create a three-column gallery that collapses to one column.","Fighting Grid with dozens of fixed pixel positions.","Use minmax to create flexible cards."),
("Responsive Design","Responsive pages adapt to different screens using flexible units, modern layout systems, and media queries.","Your users will not all have the same viewport.","Resize the preview from desktop to phone and fix overflow.","Designing for one exact device width.","Add a breakpoint only where the layout actually needs one."),
("Variables & Motion","Custom properties store reusable design values. Transitions and keyframes add feedback and personality when used intentionally.","Consistent tokens and restrained motion make interfaces feel coherent.","Create a theme variable and a subtle hover transition.","Animating everything until the interface feels noisy.","Build a tiny design system with spacing and radius variables."),
("CSS Capstone","Design a polished responsive interface for a portfolio, dashboard, course platform, game menu, or landing page.","A final build makes you combine layout, typography, responsiveness, and interaction styling.","Use Grid or Flexbox, custom properties, focus states, and one tasteful animation.","Ignoring the phone layout until the very end.","Test at a narrow width and eliminate horizontal scrolling.")
])}
]