"""Large secondary-course expansion for LearnPython."""
EXTRA = {
"html-css":[
("HTML document anatomy","Understand doctype, head, body, metadata, and browser document structure."),
("Text semantics","Use headings, paragraphs, emphasis, quotations, and code semantics correctly."),
("Navigation patterns","Build accessible navigation, skip links, breadcrumbs, and meaningful links."),
("Responsive media","Use picture, srcset, dimensions, lazy loading, and useful alt text."),
("Forms and native controls","Use labels, fieldsets, autocomplete, validation, and accessible errors."),
("Accessibility testing","Keyboard-test pages and identify semantic, focus, and labeling problems."),
("CSS cascade","Understand inheritance, specificity, layers, and source order."),
("Typography systems","Build readable type scales, line heights, font stacks, and fluid headings."),
("Modern layout","Combine Grid, Flexbox, clamp, minmax, and responsive containers."),
("Responsive components","Design cards, navbars, forms, and dashboards that adapt cleanly."),
("Design tokens","Create reusable CSS variables for spacing, type, radius, color, and motion."),
("Reduced motion","Use transitions responsibly and respect prefers-reduced-motion."),
("Performance basics","Optimize images, fonts, CSS, and layout work using evidence."),
("SEO fundamentals","Create useful titles, descriptions, headings, and crawl-friendly structure."),
("Multi-page architecture","Organize HTML and CSS so larger sites remain maintainable."),
("HTML/CSS capstone","Ship a polished, accessible, responsive multi-page website.")
],
"javascript":[
("Primitive values","Understand strings, numbers, booleans, null, undefined, equality, and conversion."),
("Objects deeply","Work with nested objects, optional chaining, and object utilities."),
("Array methods","Use map, filter, reduce, find, some, every, and sort intentionally."),
("Scope and closures","Understand lexical scope, closures, and callback behavior."),
("Destructuring and spread","Use modern syntax to unpack and compose data."),
("Modules","Split browser JavaScript into clear importable modules."),
("DOM state","Separate application state from rendering and update the UI predictably."),
("Forms and validation","Handle submit events, validation, errors, and feedback."),
("Async JavaScript","Understand promises, async/await, loading states, and failures."),
("Fetch in production","Handle HTTP status codes, JSON parsing, and network errors."),
("Browser storage","Compare localStorage, sessionStorage, and server persistence."),
("Browser security","Understand XSS risks and why client-side checks are not authorization."),
("Debugging JavaScript","Use breakpoints, network tools, console inspection, and reproducible cases."),
("Stateful mini app","Build a small app with state, rendering, events, and persistence."),
("API client architecture","Separate API calls, state, UI, and error handling."),
("JavaScript capstone","Build, test, polish, and deploy a complete browser application.")
],
"sql":[
("Primary and foreign keys","Model unique records and relationships safely."),
("NULL and three-valued logic","Understand missing values and why NULL behaves differently."),
("Subqueries","Use nested queries when they make a question clearer."),
("Common table expressions","Break complex queries into named stages with WITH."),
("CASE expressions","Turn conditions into useful derived values."),
("String and date functions","Transform common text and time data inside queries."),
("Transactions","Use commit and rollback for consistent multi-step changes."),
("Isolation basics","Understand how concurrent database operations can interact."),
("Indexes","Choose indexes from query patterns and understand their tradeoffs."),
("Query plans","Read basic execution plans and find expensive operations."),
("Normalization","Reduce duplication while preserving useful queryability."),
("Schema migrations","Change database structure safely as applications evolve."),
("Parameterized queries","Keep user input separate from SQL syntax."),
("Pagination patterns","Compare offset and cursor-style pagination."),
("Analytics queries","Combine aggregates, joins, windows, and date grouping."),
("SQL capstone","Design and query a complete schema for a real application.")
],
"git-github":[
("Git internals","Understand snapshots, trees, commits, refs, and history."),
("Staging area","Use staging deliberately to create focused commits."),
("Commit quality","Write messages that explain intent and keep history useful."),
("Branch strategy","Use short-lived branches without unnecessary complexity."),
("Merge conflicts","Resolve conflicts by understanding both sides."),
("Rebase safely","Understand when rebasing helps and when rewriting history is risky."),
("Remote tracking","Understand origin, upstream, fetch, pull, and push."),
("Tags and releases","Mark stable versions and publish useful release notes."),
("GitHub issues","Turn bugs and ideas into trackable work."),
("Pull request reviews","Read diffs, request changes, and keep reviews focused."),
("GitHub Actions","Run tests and quality checks automatically."),
("Secrets and environments","Keep credentials out of source and configure CI safely."),
("Recovery tools","Use reflog, restore, reset, and revert deliberately."),
("Monorepo basics","Understand multiple applications inside one repository."),
("Open-source workflow","Read contribution guides, issues, pull requests, and releases."),
("Git capstone","Simulate feature branch, PR, review, CI, merge, and release.")
],
"ai-ml":[
("Problem framing","Turn an AI idea into a measurable task with inputs, outputs, constraints, and a baseline."),
("Data cleaning","Handle missing values, duplicates, inconsistent labels, and leakage."),
("Feature engineering","Choose useful representations without leaking future information."),
("Train validation test","Understand why evaluation needs unseen data."),
("Metrics","Compare accuracy, precision, recall, F1, MAE, and other metrics."),
("Class imbalance","Understand why high accuracy can hide poor minority-class performance."),
("Linear models","Build intuition for simple models before deep learning."),
("Decision trees","Understand splits, depth, and overfitting."),
("Ensembles","Learn the basic idea behind forests and boosting."),
("Neural networks","Understand layers, activations, loss, optimization, and backpropagation."),
("Embeddings","Represent text or items numerically for similarity and retrieval."),
("RAG","Combine retrieval with generation while checking retrieved context."),
("Prompt engineering","Design prompts with goals, context, constraints, and examples."),
("AI evaluation","Create test sets and score outputs instead of judging one example."),
("AI security","Consider prompt injection, data leakage, permissions, and unsafe tools."),
("AI/ML capstone","Build an evaluated AI feature with documented limitations and safeguards.")
],
}
NEW = {
"react":{"title":"React","level":"Intermediate","category":"Web","description":"Build component-based interfaces with state, props, effects, forms, APIs, testing, and production patterns.","lessons":[
("React mental model","Components, rendering, props, state, and one-way data flow."),
("JSX","Write component markup and understand expressions."),
("Props","Pass data into components and design clear contracts."),
("State","Manage values that change because of user interaction."),
("Events","Handle clicks, inputs, submits, and keyboard interactions."),
("Lists and keys","Render collections using stable keys."),
("Forms","Build controlled inputs and useful validation."),
("Effects","Understand effects and when they are unnecessary."),
("Data fetching","Handle loading, success, empty, and error states."),
("Custom hooks","Extract reusable stateful behavior."),
("Component architecture","Split interfaces by responsibility."),
("Routing","Model multiple views and navigation."),
("Performance","Understand renders, memoization, and measurement."),
("Accessibility","Build keyboard-friendly, semantic React interfaces."),
("Testing","Test user-visible behavior rather than implementation details."),
("React capstone","Build and ship a complete responsive application.")
]},
"linux":{"title":"Linux & Developer Tools","level":"Beginner","category":"Tools","description":"Learn the terminal, filesystem, permissions, processes, networking, packages, SSH, scripting, logs, and troubleshooting.","lessons":[
("Terminal mental model","Understand shells, commands, arguments, stdout, stderr, and exit codes."),
("Filesystem navigation","Use pwd, ls, cd, paths, and directory structures."),
("Files and text","Create, copy, move, delete, inspect, and search files safely."),
("Pipes and redirection","Connect commands and save or transform output."),
("grep and find","Search large codebases and files efficiently."),
("Permissions","Understand users, groups, read/write/execute, and chmod."),
("Processes","Inspect programs, signals, jobs, and resource usage."),
("Environment variables","Understand PATH and process configuration."),
("Package managers","Install, update, remove, and inspect software safely."),
("SSH","Connect to remote machines and use keys safely."),
("Networking commands","Inspect DNS, ports, routes, and HTTP from the shell."),
("Shell scripting","Automate repetitive tasks with variables and loops."),
("Logs and troubleshooting","Find evidence instead of guessing at failures."),
("Services","Understand long-running processes and service managers."),
("Linux security basics","Use least privilege, updates, keys, and safe secrets."),
("Linux capstone","Build a repeatable developer/server workflow from the shell.")
]},
"cybersecurity":{"title":"Cybersecurity Fundamentals","level":"Beginner","category":"Security","description":"Learn defensive security: threats, authentication, authorization, web security, cryptography, privacy, monitoring, and secure development.","lessons":[
("Security mindset","Think in assets, threats, vulnerabilities, impact, and controls."),
("Threat modeling","Map trust boundaries and likely abuse cases before coding."),
("Authentication","Understand passwords, sessions, MFA, and account recovery."),
("Authorization","Separate identity from permissions and enforce access server-side."),
("Password security","Learn hashing, salts, rate limits, and credential hygiene."),
("Web security","Understand XSS, CSRF, injection, and broken access control."),
("Cryptography basics","Distinguish hashing, encryption, signatures, keys, and randomness."),
("TLS and HTTPS","Understand what HTTPS protects and what it does not."),
("Secrets management","Keep API keys and credentials out of source and logs."),
("Secure APIs","Validate input, authenticate requests, and limit abuse."),
("Dependency security","Track dependencies and understand supply-chain risk."),
("Security logging","Create useful logs without collecting unnecessary sensitive data."),
("Backups and recovery","Plan for data loss and accidental deletion."),
("Incident response","Identify, contain, investigate, recover, and learn."),
("Privacy by design","Collect less data, protect what you keep, and define retention."),
("Security capstone","Threat-model and harden a small application.")
]}
}
def apply_expansion(courses):
    for slug, extra in EXTRA.items():
        if slug in courses:
            courses[slug]["lessons"].extend(extra)
    for slug, course in NEW.items():
        courses.setdefault(slug, course)
    return courses
