"""Master curriculum pack: 15 tracks, each from Beginner to Master."""
TRACKS = {
"dart":("Dart","DART","Dart from zero to production.", "Setup,syntax & main|Variables,types & null safety|Collections & control flow|Functions,closures & records|Classes & constructors|Generics & extensions|Mixins & interfaces|Async,Futures & Streams|Packages & tooling|Testing & debugging|Isolates & concurrency|Memory & performance|Error handling & observability|Networking & JSON|Library and package design|Clean architecture|State and dependency boundaries|Production CLI/service|Security and deployment|Master capstone"),
"kotlin":("Kotlin","KOTLIN","Kotlin from zero to master with null safety, coroutines and JVM engineering.", "Setup,syntax & main|Variables,types & expressions|Null safety|Collections & control flow|Functions & lambdas|Classes,objects & constructors|Interfaces,sealed classes & data classes|Generics & variance|Coroutines & structured concurrency|Testing and Gradle|JVM interop|Flows and reactive pipelines|Performance and memory|Networking and serialization|Error handling and resilience|Modular architecture|Dependency injection and boundaries|Production service design|Security,observability and deployment|Master capstone"),
"java":("Java","JAVA","Java from first principles to master-level JVM engineering.", "Setup,classes & main|Variables,types & operators|Conditionals and loops|Arrays,strings & collections|Methods and exceptions|Classes and encapsulation|Inheritance,interfaces & records|Generics & functional APIs|Concurrency and executors|Maven/Gradle and testing|JVM memory model|Threads,locks and atomics|Performance profiling|HTTP clients and serialization|Database access and transactions|Modular application architecture|API and service design|Resilience and observability|Security and deployment|Master capstone"),
"cpp":("C++","C++","Modern C++ from zero through memory ownership, templates and systems design.", "Setup,compilation & main|Variables,types & operators|Control flow|Arrays,strings & vectors|Functions and references|Classes and RAII|Pointers and smart pointers|Templates and STL|Move semantics and concurrency|CMake and testing|Memory model|Threading and synchronization|Performance and profiling|File,network and serialization boundaries|Error handling and API design|Library architecture|Generic programming at scale|Systems-level optimization|Security and production builds|Master capstone"),
"csharp":("C#","C#","Modern C# and .NET from zero to production architecture.", "Setup,projects & main|Types,variables & operators|Control flow|Arrays,strings & collections|Methods and exceptions|Classes,records & properties|Interfaces,generics & delegates|LINQ|Async/await and tasks|NuGet,testing and tooling|Memory and spans|Concurrency and channels|Performance profiling|HTTP,JSON and persistence|Error handling and resilience|.NET application architecture|API and service boundaries|Observability and deployment|Security and production hardening|Master capstone"),
"rust":("Rust","RUST","Rust from zero to master with ownership, async and systems engineering.", "Setup,cargo & main|Variables,types & control flow|Ownership basics|Borrowing and references|Structs,enums and pattern matching|Traits and generics|Collections and iterators|Lifetimes|Result,Option and error design|Testing and Cargo tooling|Concurrency and Send/Sync|Async Rust|Memory and performance|FFI and unsafe boundaries|Networking and serialization|Crate and workspace architecture|API design and resilience|Systems optimization|Security and production deployment|Master capstone"),
"swift":("Swift","SWIFT","Swift from zero to master with protocols, concurrency and architecture.", "Setup,syntax & main|Types,variables & optionals|Control flow|Collections and strings|Functions and closures|Structs,classes and enums|Protocols and extensions|Generics and result types|Concurrency with async/await|Packages and testing|Actors and isolation|Memory and value semantics|Performance and profiling|Networking and Codable|Error handling and resilience|Module and architecture design|Dependency boundaries|Production service/app structure|Security and release engineering|Master capstone"),
"php":("PHP","PHP","Modern PHP from zero through web development, APIs and production engineering.", "Setup and first script|Variables,types and operators|Control flow|Arrays and strings|Functions and files|Classes and namespaces|Interfaces,traits and exceptions|Composer and autoloading|HTTP and forms|Testing and debugging|PDO and transactions|Sessions and authentication|REST APIs and JSON|Caching and performance|Queues and background work|Application architecture|Framework concepts and boundaries|Observability and deployment|Web security hardening|Master capstone"),
"ruby":("Ruby","RUBY","Ruby from zero to master with OOP, blocks, testing and web architecture.", "Setup and first script|Variables,objects and types|Control flow|Arrays,hashes and strings|Methods and blocks|Classes and modules|Mixins and enumerables|Exceptions and files|Gems and Bundler|Testing and debugging|Blocks,Proc and lambda|Metaprogramming safely|Concurrency and background jobs|HTTP and JSON|Database and transactions|Application architecture|API and service boundaries|Performance and observability|Security and deployment|Master capstone"),
"r":("R","R","R from zero to master for programming, statistics and reproducible analysis.", "Setup and R basics|Vectors,types and indexing|Conditions and loops|Functions|Lists,data frames and tibbles|Data transformation|Factors and missing data|Visualization foundations|Packages and reproducibility|Testing and project structure|Statistical modeling|Regression and diagnostics|Performance and vectorization|Data ingestion and APIs|Error handling and reproducible pipelines|Analysis architecture|Reusable packages and reports|Production data workflows|Security and deployment considerations|Master capstone"),
"bash-linux":("Bash & Linux","BASH","Linux and Bash from zero to master for automation and production operations.", "Terminal and filesystem|Paths,files and permissions|Commands and pipes|Variables and quoting|Shell scripts and arguments|Conditionals and loops|Functions and exit codes|Text processing|Processes and jobs|Package and service management|Signals and process control|Networking and diagnostics|Logs and observability|Cron and automation|Shell security|Production server architecture|Backups and recovery|Deployment automation|Hardening and incident response|Master capstone"),
"react":("React","REACT","React from zero to master with state, performance, accessibility and architecture.", "Setup and first component|JSX and props|Events and conditional UI|Lists and keys|State with useState|Forms and controlled inputs|Effects and data fetching|Context and custom hooks|Routing and application structure|Testing and debugging|Rendering model|Performance and memoization|State architecture|API and caching boundaries|Error handling and resilience|Component architecture|Design systems and accessibility|Production build and observability|Security and deployment|Master capstone"),
"nodejs":("Node.js","NODE","Node.js from zero to master for APIs, databases and production systems.", "Runtime and first script|Modules and npm|Variables and JavaScript fundamentals|Async callbacks and promises|Filesystem and paths|HTTP servers|Routing concepts|Validation and API design|Databases and persistence|Testing and debugging|Event loop and concurrency|Streams and backpressure|Caching and performance|Queues and workers|Observability and errors|Service architecture|Authentication and authorization|Production deployment|Security and resilience|Master capstone"),
"docker":("Docker","DOCKER","Docker from zero to master with images, networking, CI/CD and hardening.", "Containers and images|Dockerfile basics|Build context and layers|Ports and networking|Volumes and persistence|Environment and configuration|Compose fundamentals|Health checks and dependencies|Debugging containers|Image optimization|Multi-stage builds|Container security|Resource limits|Registries and image promotion|Logging and observability|Production Compose architecture|CI/CD container pipelines|Orchestration concepts|Supply-chain hardening|Master capstone"),
"flutter":("Flutter","FLUTTER","Flutter from zero to master for production mobile and desktop apps.", "Flutter setup and first app|Widget tree and build|Layouts and constraints|Text,images and assets|Input and gestures|State with StatefulWidget|Lists and forms|Navigation and routes|Async data and HTTP|Testing and debugging|State architecture|Rendering and performance|Animations|Persistence and offline data|Error handling and resilience|Feature-based architecture|Design systems and accessibility|Release builds and observability|Security and deployment|Master capstone")
}

def lesson(course,level,part,title,index,total):
    if index == total:
        focus=f"Build a complete {course} capstone that combines the track instead of demonstrating isolated syntax."
        practice="Plan the architecture, implement a thin vertical slice, add tests, then harden and document the release."
        mistake="Confusing mastery with memorizing APIs instead of making sound engineering trade-offs."
        levelup="Document architecture decisions, failure modes, performance assumptions, security controls and maintenance."
    else:
        focus=f"{title} is a core {course} concept. Learn its mental model, then connect it to code, tooling, failure modes and production trade-offs."
        practice=f"Build a tiny {course} exercise for {title}; change one assumption, run it, and explain the result."
        mistake=f"Memorizing {title} without understanding the boundary between your code and the runtime, framework, OS or network."
        levelup=f"Extend {title} with validation, tests, error handling and one measurable improvement."
    flow=f"Input → {title} → {level} → Practice → Tested result"
    return {"title":title,"part":part,"level":level,"body":f"Level: {level}\nPart: {part}\n\nIn Plain English\n{focus}\n\nDIAGRAM: {flow}\n\nWhy This Matters\nThis is part of the {level} stage. You should understand not only how to use the concept, but when to use it and what can go wrong.\n\nTry It Yourself\n{practice}\n\nCommon Mistake\n{mistake}\n\nLevel Up\n{levelup}"}

def make(slug,spec):
    title,tag,desc,raw=spec
    names=raw.split("|")
    out=[]
    for i,name in enumerate(names,1):
        level="Beginner" if i<=5 else "Intermediate" if i<=10 else "Advanced" if i<=15 else "Master"
        part="Part 1 — Foundations" if i<=5 else "Part 2 — Building" if i<=10 else "Part 3 — Engineering" if i<=15 else "Part 4 — Mastery"
        out.append(lesson(title,level,part,name,i,len(names)))
    return {"slug":slug,"title":title,"tag":tag,"description":desc,"lessons":out,"levels":["Beginner","Intermediate","Advanced","Master"]}

COURSES=[make(slug,spec) for slug,spec in TRACKS.items()]
