"""Expanded Python curriculum for LearnPython.
Loaded after the original 47 lessons so existing lesson IDs remain stable.
"""

PYTHON_EXPANSION = [
("48","Pythonic Thinking","Write code that follows Python's strengths: clear iteration, unpacking, comprehensions, context managers, and readable data transformations.","Pythonic code is not about clever one-liners; it is about expressing intent clearly.","Rewrite a nested loop using enumerate or a comprehension where it genuinely improves clarity.","Over-compressing code until nobody can read it.","Compare a compact solution with a clear multi-line solution and choose deliberately."),
("49","Advanced Function Patterns","Explore positional and keyword arguments, *args, **kwargs, keyword-only parameters, and small functional patterns.","Good function interfaces make code easier to reuse and test.","Build a function that accepts a required name plus optional keyword settings.","Using *args and **kwargs when explicit parameters would be clearer.","Design a function API for a small logging helper."),
("50","Scope, LEGB & Closures","Understand local, enclosing, global, and built-in name lookup and how closures retain state.","Scope explains many surprising Python behaviors.","Create a closure that remembers a counter between calls.","Using global state when a small object or closure would be safer.","Trace where Python finds three different variable names."),
("51","Dataclasses","Use dataclasses to model structured records with readable defaults, generated methods, and type annotations.","They remove repetitive boilerplate from many data-heavy classes.","Create a Product dataclass with validation-friendly fields.","Putting complex business logic into a data container without a reason.","Convert an ordinary record class into a dataclass and compare it."),
("52","Enums & Constants","Use Enum for named states and constants instead of scattering magic strings or numbers through a program.","Named states make code and validation easier to understand.","Create a Status enum with pending, active, and complete.","Comparing enum members to unrelated strings everywhere.","Use an enum in a task workflow."),
("53","Type Hints Deep Dive","Use annotations for collections, Optional-style values, unions, callable types, and reusable aliases.","Type hints improve editor feedback and make larger Python codebases easier to navigate.","Annotate a small API client or task manager.","Assuming type hints validate input at runtime.","Add type hints to one earlier project without changing its behavior."),
("54","Protocols & Structural Typing","Learn the idea behind structural typing: code can depend on behavior instead of one concrete class hierarchy.","This is useful for flexible libraries and testable architecture.","Define a protocol-like interface for objects that can save data.","Adding abstractions before you have a real need for them.","Swap a real repository for a fake test repository."),
("55","Itertools","Use itertools tools such as chain, islice, product, combinations, and groupby for efficient iteration.","The standard library already solves many iteration problems elegantly.","Generate combinations of project features without nested loops.","Forgetting that some iterators are consumed as you iterate.","Build a tiny combination generator."),
("56","Collections Module","Use Counter, defaultdict, deque, and named structures when ordinary lists and dictionaries are awkward.","Choosing the right standard-library structure can simplify code dramatically.","Count words with Counter and build a queue with deque.","Using a complicated custom structure for a simple problem.","Replace one manual counting loop with Counter."),
("57","Pathlib","Use pathlib for readable, cross-platform filesystem paths instead of fragile string concatenation.","File-heavy programs become much easier to maintain.","List Python files recursively in a project directory.","Mixing Windows and POSIX path separators manually.","Build a file inventory that reports extensions and sizes."),
("58","Logging Properly","Replace scattered print statements with logging levels, formatters, and useful context.","Production programs need diagnostics that can be controlled without editing code.","Log startup, a successful operation, and an exception.","Logging passwords, tokens, or unnecessary personal data.","Design INFO/WARNING/ERROR messages for one project."),
("59","Configuration & Environment Variables","Separate configuration from code using environment variables and safe defaults.","Deployment settings should not require editing source code.","Read a port and feature flag from the environment.","Committing secrets or relying on machine-specific absolute paths.","Create a development configuration with safe defaults."),
("60","JSON APIs & Validation","Work with structured JSON while treating external data as untrusted input that must be checked.","Real applications constantly cross API boundaries.","Parse JSON and validate required fields before using them.","Assuming a JSON response always has the fields you expect.","Write a small validation function that returns clear errors."),
("61","HTTP Clients & Retries","Build reliable HTTP calls with timeouts, status handling, retries, and backoff.","Networks fail; robust clients expect that.","Design a request helper with a timeout and limited retries.","Retrying every error forever or retrying unsafe operations blindly.","Classify failures into retryable and non-retryable."),
("62","Asyncio Fundamentals","Understand event loops, coroutines, tasks, await, and when asynchronous I/O helps.","Async programming is valuable for many I/O-heavy tools and services.","Create several coroutines that wait different amounts of time.","Using async syntax without understanding what is actually concurrent.","Compare sequential waits with asyncio.gather."),
("63","Concurrency: Threads vs Processes","Understand the practical difference between threads, processes, and asynchronous I/O.","The right concurrency model depends on whether work is I/O-bound or CPU-bound.","Classify ten example workloads by the best concurrency model.","Assuming more workers always means more performance.","Benchmark a small I/O task with a few worker counts."),
("64","Testing Strategy","Move beyond single happy-path tests into edge cases, fixtures, parametrization, and testable design.","Testing should protect behavior rather than merely increase a percentage.","Write tests for empty input, invalid input, and normal input.","Testing only the implementation details instead of observable behavior.","Turn three manual checks into automated tests."),
("65","Mocking & Dependency Boundaries","Use mocks or fakes at external boundaries such as APIs, files, clocks, and payment systems.","Tests become faster and deterministic when external systems are isolated.","Replace an API client with a fake object in a unit test.","Mocking everything until the test no longer resembles real behavior.","Choose one dependency that genuinely deserves a fake."),
("66","Packaging a Real Project","Understand package layout, pyproject.toml, dependencies, entry points, and reproducible environments.","A project becomes easier to install, test, and share when its structure is deliberate.","Turn a small script into an installable package layout.","Treating a folder of scripts as a maintainable package automatically.","Sketch the files needed for a publishable Python CLI."),
("67","SQLite Beyond Basics","Use transactions, parameterized queries, indexes, and schema design with sqlite3.","Database code needs correctness and safe query construction.","Create a users/tasks schema and query it with parameters.","Building SQL strings with user input.","Add an index and explain which query it helps."),
("68","Database Design for Apps","Think in entities, relationships, keys, constraints, and migrations before writing a pile of tables.","Good schemas reduce duplicated and inconsistent data.","Design tables for users, courses, lessons, and progress.","Putting the same data in every row because it feels simpler initially.","Identify one-to-many and many-to-many relationships in a learning platform."),
("69","Flask Architecture","Separate routes, business logic, templates, configuration, and persistence as an application grows.","A framework project becomes easier to change when responsibilities are separated.","Move one route's business logic into a helper/service function.","Putting database queries, HTML, and validation into one giant function.","Draw a simple request → service → database flow."),
("70","Flask Forms & Validation","Validate form input, handle errors, preserve user experience, and keep server-side validation authoritative.","Browser validation is useful but never the security boundary.","Build a registration form with server-side validation.","Trusting hidden fields or client-side checks.","Return field-specific errors without leaking sensitive details."),
("71","Sessions, Cookies & CSRF","Understand sessions, cookie flags, CSRF tokens, and why state-changing requests need protection.","Web authentication depends on secure state management.","Explain why HttpOnly, SameSite, Secure, and CSRF each exist.","Treating a cookie as proof that every request is trustworthy.","Threat-model a login form and its state-changing actions."),
("72","Password Security","Store passwords with slow password-hashing algorithms and never store plaintext passwords.","Authentication security begins with protecting the credential database.","Explain hashing versus encryption using a password example.","Logging passwords or storing reversible password encryption.","Review a mock signup flow and identify credential risks."),
("73","Web Security Fundamentals","Learn XSS, SQL injection, CSRF, open redirects, insecure file handling, and least privilege at a practical level.","Knowing common attack classes changes how you design input and output.","Find the unsafe line in a deliberately vulnerable example.","Assuming escaping alone solves every web security problem.","Create a checklist for a small Flask application."),
("74","REST API Design","Design predictable resources, HTTP methods, status codes, validation, pagination, and error responses.","A clean API is easier for browsers, mobile apps, and other services to consume.","Design endpoints for courses, lessons, and progress.","Returning a different response shape for every endpoint.","Write an API contract for one resource."),
("75","Background Jobs","Understand queues, scheduled work, idempotency, retries, and jobs that should not block web requests.","Email, imports, reports, and long processing often belong outside request/response time.","Design a job that sends a course completion email.","Running unbounded work directly inside a request handler.","Define retry behavior and an idempotency key."),
("76","Caching & Performance","Learn what to cache, cache invalidation basics, database query costs, and measuring before optimizing.","Performance work should be driven by evidence rather than guesses.","Identify one expensive operation and define a useful metric.","Adding caching before knowing whether anything is slow.","Measure a route before and after one targeted optimization."),
("77","Python Profiling","Use time measurements and profilers to locate slow functions instead of optimizing by intuition.","Profiling turns performance debugging into an evidence-based process.","Profile a deliberately slow list-processing function.","Optimizing code that is not a real bottleneck.","Write down the bottleneck, hypothesis, change, and result."),
("78","Clean Architecture in Practice","Use boundaries and small modules to keep a project understandable without creating needless abstraction.","Architecture should make change safer, not make simple code harder to read.","Split a mini app into domain, persistence, and interface layers.","Creating ten layers for a fifty-line script.","Refactor one feature while keeping its tests unchanged."),
("79","Command-Line Interfaces","Build polished CLIs with arguments, subcommands, validation, exit codes, and helpful output.","CLI tools are a practical way to turn Python into reusable software.","Design a course-progress CLI with list and mark-complete commands.","Printing errors but still returning success exit codes.","Make invalid input produce a useful message and non-zero exit."),
("80","Automation with Scheduling","Combine Python scripts with scheduling concepts for recurring reports, cleanup, backups, or reminders.","Automation becomes powerful when it is reliable and observable.","Design a daily report job that can safely run twice.","Assuming scheduled jobs always run exactly once.","Make a job idempotent and log its result."),
("81","Data Pipelines","Build a small pipeline that extracts, transforms, validates, and loads data.","ETL thinking applies to analytics, imports, migrations, and automation.","Transform a CSV into cleaned records and a summary.","Mixing validation and output so failures are hard to diagnose.","Add explicit stages and a rejected-record report."),
("82","Pandas Beyond the Basics","Use indexing, grouping, merging, missing values, and vectorized operations for practical data work.","Real datasets are messy; basic dataframe operations only get you so far.","Clean a small dataset with missing values and duplicate rows.","Looping over every row when a vectorized operation exists.","Explain why a groupby result has its current shape."),
("83","NumPy Fundamentals","Understand arrays, shapes, dtypes, broadcasting, and vectorized numeric operations.","NumPy is the foundation underneath much of Python's numerical ecosystem.","Create an array and perform an operation without a Python loop.","Mixing incompatible shapes without checking what broadcasting does.","Predict the shape of a broadcasted result."),
("84","Regular Expressions in Real Projects","Use regex for targeted extraction and validation while knowing when ordinary string methods are better.","Regex is powerful but can become unreadable if used everywhere.","Extract structured IDs from sample text.","Writing a giant regex for a problem that split() solves clearly.","Add named groups to make a pattern understandable."),
("85","Serialization & Pickle Safety","Compare JSON and safer data formats with Python-specific serialization, including why untrusted pickle data must never be loaded.","Serialization is a boundary between data and executable behavior.","Choose JSON or another format for three use cases.","Treating every serialization format as equally safe.","Explain why untrusted pickle is dangerous."),
("86","Memory & Generators","Use generators and streaming techniques when data is too large to hold comfortably in memory.","Efficient programs often process data incrementally.","Stream lines from a large file and count matching records.","Calling list() on a huge generator without considering memory.","Compare a list-based and generator-based approach."),
("87","Packaging, CI & Quality Gates","Combine formatting, linting, tests, and CI checks so every change gets basic automated verification.","Quality gates catch regressions before deployment.","Define checks for a small Python repository.","Making CI so slow or strict that nobody uses it effectively.","Choose a minimal but useful CI pipeline."),
("88","Capstone: Learning Platform API","Design a small Flask API for courses, lessons, accounts, and progress with validation and secure persistence.","This combines Python language skills with real application architecture.","Implement one resource end-to-end before adding the next.","Trying to build every endpoint at once.","Add tests for authentication, authorization, validation, and progress updates."),
("89","Capstone: Production Checklist","Review configuration, logging, errors, database migrations, security headers, backups, tests, and deployment health checks.","Shipping software means operating it, not just making it run once.","Create a release checklist for a Flask app.","Assuming a successful local run means production is safe.","Perform a pre-release review and record unresolved risks."),
("90","Python Mastery Project","Build one substantial project that uses your own idea: automation tool, API, data app, CLI, web app, or developer tool.","The goal is independent problem solving rather than copying a tutorial.","Write requirements, split the project into milestones, and ship a usable v1.","Adding features before the core workflow works.","Document architecture, setup, tests, and known limitations.")
]

def extend_python(course):
    for raw_n,title,body,why,tryit,mistake,level in PYTHON_EXPANSION:
        course.append({"n":int(raw_n),"title":title,"part":"Part 6 — Intermediate & Production Python",
                     "body":f"{title}\nIn Plain English\n{body}\n\nWhy This Matters\n{why}\n\nTry It Yourself\n{tryit}\n\nCommon Mistake\n{mistake}\n\nLevel Up\n{level}"})
    return course
