"""Extended Python curriculum.

The original 47 lessons remain unchanged. These modules continue the path into
intermediate and practical Python engineering.
"""

def _lesson(n, title, part, focus, practice, mistake, level):
    return {
        "n": n,
        "title": title,
        "part": part,
        "body": (
            f"Chapter {n}: {title}\n"
            f"In Plain English\n{focus}\n\n"
            "Why This Matters\n"
            f"{focus} This becomes useful when your programs grow beyond small exercises.\n\n"
            "Try It Yourself\n"
            f"{practice}\n\n"
            "Common Mistake\n"
            f"{mistake}\n\n"
            "Level Up\n"
            f"{level}"
        )
    }

def build(start=48):
    rows = [
("Pythonic Thinking","Part 7 — Intermediate Python","Pythonic code favors clear, direct use of the language rather than copying patterns from other languages. Readability is a feature.","Take one older exercise and rewrite it using normal Python idioms.","Making code shorter at the cost of clarity.","Compare both versions and keep the one a new developer can understand."),
("Scope & Namespaces","Part 7 — Intermediate Python","Names live in scopes. Local, enclosing, global, and built-in scopes explain why a variable is or is not visible.","Create nested functions and predict which name each one sees.","Using global state to solve every scope problem.","Pass values explicitly and use closures only when they clarify the design."),
("Mutable Defaults & Gotchas","Part 7 — Intermediate Python","Default arguments are evaluated when a function is defined, not every time it is called.","Reproduce the mutable-list default argument bug and fix it.","Using [] or {} as a default when a fresh object is required.","Use None as the sentinel and create the object inside the function."),
("Copying Objects","Part 7 — Intermediate Python","Assignment binds another name to an object; shallow and deep copies create different levels of independence.","Compare assignment, copy.copy, and copy.deepcopy on nested data.","Assuming every assignment creates a new object.","Choose the minimum copying needed and understand nested references."),
("Dataclasses","Part 7 — Intermediate Python","dataclasses reduce boilerplate for classes that primarily represent structured data.","Turn a small record class into a dataclass.","Adding dataclasses to behavior-heavy classes without a reason.","Use dataclasses when generated representation and comparison behavior are useful."),
("Type Hints in Practice","Part 7 — Intermediate Python","Type hints document expectations for variables, parameters, and return values without changing Python's runtime model.","Annotate one existing project from top to bottom.","Adding vague Any annotations everywhere.","Use precise types at boundaries and run a static type checker."),
("Protocols & Structural Typing","Part 7 — Intermediate Python","A protocol describes the behavior an object must provide, allowing compatible types without inheritance.","Define a protocol for an object that can save data.","Requiring inheritance when only behavior matters.","Keep protocols small and focused."),
("Enums & Constants","Part 7 — Intermediate Python","Enums model a fixed set of named choices and can make state easier to understand.","Replace magic strings for application states with an enum.","Creating enums for values that genuinely vary.","Use named constants or enums when they improve correctness and readability."),
("Context Managers","Part 7 — Intermediate Python","Context managers guarantee setup and cleanup around a block, commonly through with.","Use with open(...) and then create a custom context manager.","Manually duplicating cleanup in every branch.","Make cleanup automatic when resources have a clear lifetime."),
("Advanced Iteration","Part 7 — Intermediate Python","Iteration protocols explain how for loops consume iterators and how iterable objects can define __iter__.","Create a small custom iterable.","Returning a list when a lazy iterator is more appropriate.","Keep iteration behavior predictable and finite."),
("Generator Pipelines","Part 7 — Intermediate Python","Generators can form lazy pipelines that transform data without creating every intermediate list.","Build a pipeline that filters and transforms a large sequence.","Materializing huge intermediate collections unnecessarily.","Measure memory behavior and keep the pipeline readable."),
("Decorators in Depth","Part 7 — Intermediate Python","Decorators wrap functions or classes to add behavior such as logging, caching, or authorization.","Write a decorator that measures execution time.","Forgetting functools.wraps and losing useful metadata.","Keep decorators small and explicit."),
("Caching & Memoization","Part 7 — Intermediate Python","Caching stores previous results so repeated expensive work can be avoided.","Memoize a recursive calculation and compare it with the uncached version.","Caching everything without considering memory or stale data.","Define when cached data is valid and when it must expire."),
("Logging Properly","Part 7 — Intermediate Python","The logging module gives applications structured levels and configurable output instead of scattered print statements.","Replace debug prints in a small script with logging.","Logging passwords, tokens, or sensitive user data.","Choose levels deliberately and keep secrets out of logs."),
("Configuration Management","Part 7 — Intermediate Python","Configuration should be separate from code so environments can change behavior safely.","Design configuration for development and production.","Hard-coding secrets or deployment-specific paths.","Use environment variables or configuration files and validate them at startup."),
("Command-Line Interfaces","Part 7 — Intermediate Python","argparse can turn a Python script into a predictable command-line application.","Build a CLI with subcommands and help text.","Parsing every argument manually from sys.argv.","Give users clear help, defaults, and errors."),
("Environment Variables","Part 7 — Intermediate Python","Environment variables provide runtime configuration without embedding deployment values in source code.","Read a configurable API endpoint from the environment.","Committing API keys to the repository.","Validate required variables at startup and provide safe defaults only when appropriate."),
("Packaging a Python Project","Part 7 — Intermediate Python","A package needs predictable metadata, structure, and installation behavior.","Turn a small module into an installable project.","Relying on the current working directory for imports.","Use a standard package layout and test installation in a clean environment."),
("Dependency Management","Part 7 — Intermediate Python","Dependencies should be explicit and reproducible so another machine can install the same project requirements.","Create a dependency list for a small app.","Installing packages globally and assuming everyone has them.","Pin or constrain important dependencies and keep environments isolated."),
("Logging, Errors & Boundaries","Part 7 — Intermediate Python","Reliable applications decide where errors are handled, where they are logged, and what users are told.","Design an error boundary for a CLI application.","Catching Exception everywhere and continuing silently.","Handle errors where you can actually recover from them."),
("Testing with pytest","Part 8 — Professional Python","pytest makes focused tests concise and encourages small, repeatable checks around behavior.","Write tests for a calculator, parser, and validation function.","Writing tests that only reproduce the implementation.","Test behavior, edge cases, and failures."),
("Fixtures & Test Design","Part 8 — Professional Python","Fixtures prepare reusable test data and resources without duplicating setup in every test.","Design a fixture for a temporary user record.","Sharing mutable test state between cases.","Keep tests isolated and deterministic."),
("Mocking External Services","Part 8 — Professional Python","Mocks replace slow or unavailable external dependencies so application logic can be tested independently.","Mock an API client in a unit test.","Mocking every internal function until the test proves nothing.","Mock at the system boundary and test real integrations separately."),
("Asyncio Fundamentals","Part 8 — Professional Python","asyncio runs cooperative asynchronous tasks and is useful for I/O-heavy workloads.","Run several simulated async tasks concurrently.","Assuming async automatically speeds CPU-heavy work.","Use async when waiting dominates the workload."),
("Async HTTP Clients","Part 8 — Professional Python","Async HTTP clients can make many independent network requests without blocking on each one sequentially.","Design a bounded async API fetcher.","Launching hundreds of requests without limits.","Use timeouts, concurrency limits, and error handling."),
("Concurrency Choices","Part 8 — Professional Python","Threads, processes, and asyncio solve different workload shapes.","Choose an approach for CPU work, blocking I/O, and many network waits.","Choosing a concurrency model based on hype.","Describe the bottleneck before choosing the tool."),
("Queues & Workers","Part 8 — Professional Python","A queue decouples producers from workers and can smooth bursts of work.","Build a conceptual background job queue.","Letting producers create unlimited work.","Bound the queue and define retry behavior."),
("SQLite in Real Projects","Part 8 — Professional Python","SQLite is a capable embedded database when a full server database is unnecessary.","Design a small schema and transaction for an offline app.","Building SQL strings with user input.","Use parameterized queries and explicit transactions."),
("Database Transactions","Part 8 — Professional Python","Transactions make a group of database changes succeed or fail together.","Transfer a value between two records atomically.","Updating one record and forgetting the second when an error occurs.","Commit only after every required change succeeds."),
("SQL Injection Defense","Part 8 — Professional Python","SQL injection happens when untrusted input changes the meaning of a query.","Find the unsafe query in a toy example.","Concatenating user input into SQL.","Use parameterized queries everywhere input reaches SQL."),
("HTTP APIs with Flask","Part 9 — Web Development","A Flask API maps HTTP requests to application logic and returns structured responses.","Create a health endpoint and a JSON endpoint.","Putting all business logic directly in route functions.","Separate routing, validation, and service logic."),
("API Validation","Part 9 — Web Development","Incoming JSON is untrusted data and should be validated before application code uses it.","Design validation for a registration payload.","Trusting fields because the frontend already checks them.","Validate again on the server and return safe errors."),
("Authentication Concepts","Part 9 — Web Development","Authentication answers who a user is; authorization answers what that user can do.","Map login, session, and protected-route behavior.","Treating a hidden frontend button as authorization.","Enforce permissions on the server."),
("Sessions & Cookies","Part 9 — Web Development","Sessions let a server associate requests with a logged-in user while cookies carry session information.","Explain how a browser sends a session cookie back to a server.","Putting sensitive application data directly into a client-controlled cookie.","Use secure, HTTP-only cookies and server-side authorization."),
("CSRF Protection","Part 9 — Web Development","Cross-site request forgery can cause a logged-in browser to submit an unwanted state-changing request.","Identify which form actions need CSRF protection.","Protecting only GET requests while leaving writes open.","Use CSRF tokens for state-changing browser requests."),
("Secure Password Storage","Part 9 — Web Development","Passwords should be stored as slow password hashes rather than plaintext or reversible encryption.","Explain why a hash database can still be attacked.","Storing passwords directly or using a fast general-purpose hash.","Use a password hashing scheme designed for passwords."),
("Security Headers","Part 9 — Web Development","Headers can reduce browser attack surface through policies for framing, content types, referrers, and more.","Choose useful headers for a small web app.","Adding a header without checking whether it breaks required functionality.","Start with a documented security policy and test it."),
("Input Limits & Rate Limiting","Part 9 — Web Development","Limiting request size and repeated attempts protects endpoints from abuse and accidental overload.","Design limits for login and registration.","Applying unlimited retries to authentication endpoints.","Use sensible per-route limits and monitor failures."),
("Web Deployment Basics","Part 10 — Shipping Python","A deployed app needs a production server, environment configuration, logs, and a health check.","Write a deployment checklist for a Flask app.","Using the development server as the production architecture.","Use a production WSGI server and verify health after deploy."),
("Environment Separation","Part 10 — Shipping Python","Development and production should not accidentally share secrets, databases, or debug settings.","List configuration that must differ between environments.","Leaving debug mode enabled in production.","Make environment-specific settings explicit."),
("Observability","Part 10 — Shipping Python","Logs, metrics, health checks, and useful error context make deployed systems diagnosable.","Design three health signals for a small service.","Logging only successful requests.","Log failures with enough context to investigate without leaking secrets."),
("Performance Profiling","Part 10 — Shipping Python","Profiling shows where time and memory actually go.","Plan a benchmark for a slow function.","Optimizing based on intuition alone.","Measure before and after every meaningful optimization."),
("Memory & Large Data","Part 10 — Shipping Python","Large datasets can exhaust memory when fully loaded; iterators and streaming can reduce peak usage.","Rewrite a list-building task as a generator pipeline.","Loading an entire huge file into memory unnecessarily.","Process data incrementally when possible."),
("Caching Strategies","Part 10 — Shipping Python","Caching can reduce repeated expensive work but introduces invalidation and freshness concerns.","Design a cache for a read-heavy endpoint.","Caching mutable data forever.","Define TTL, invalidation, and ownership of cached values."),
("Background Jobs","Part 10 — Shipping Python","Long-running work should often run outside a request so users are not forced to wait.","Design a background email or report job.","Keeping long tasks inside a web request indefinitely.","Return a job state and process work separately."),
("Architecture: Routes, Services, Repositories","Part 10 — Shipping Python","Separating HTTP, business rules, and persistence can make larger Python applications easier to test.","Refactor one route into three layers on paper.","Adding layers without clear responsibilities.","Keep boundaries small and justified."),
("Capstone Architecture","Part 11 — Advanced Projects","A real application starts with requirements, data flow, boundaries, and failure cases before code volume.","Design an architecture for a course platform with users and progress.","Starting with UI screens before deciding how data and permissions work.","Write a one-page technical design first."),
("Capstone: CLI Application","Part 11 — Advanced Projects","A production-style CLI combines parsing, validation, persistence, errors, tests, and clean output.","Build a task manager or expense tracker with SQLite.","Adding features before the core command loop works.","Ship a small vertical slice first."),
("Capstone: Web API","Part 11 — Advanced Projects","A web API combines routing, validation, authentication, persistence, and security controls.","Build a small course-progress API.","Trusting the client to enforce authorization.","Test unauthorized and malformed requests."),
("Capstone: Automation Tool","Part 11 — Advanced Projects","Automation scripts become reliable when they validate inputs, handle failures, and produce useful logs.","Build a file organizer or report generator.","Deleting or overwriting files without a dry run.","Add a preview mode and safe defaults."),
("Capstone: Data Pipeline","Part 11 — Advanced Projects","A data pipeline reads, transforms, validates, and stores information in stages.","Build a CSV-to-report pipeline.","Silently accepting malformed records.","Track rejected rows and produce a summary."),
("Capstone: Production Checklist","Part 11 — Advanced Projects","Shipping means testing, configuration, security, observability, backups, and rollback thinking.","Create a release checklist for your project.","Calling the project finished when it merely runs locally.","Verify the failure path as carefully as the happy path.")
    ]
    return [_lesson(start+i, *row) for i,row in enumerate(rows)]

EXTENDED_PYTHON = build()
